services:
  nestjs-dashboard-api:
    image: nestjs-dashboard-api
    container_name: nestjs-dashboard-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - '3000:3000'
    networks:
      - nestjs-dashboard-network

  db:
    image: postgres:16
    container_name: nestjs-dashboard-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'UTC'
    ports:
      - '25432:5432'
    networks:
      - nestjs-dashboard-network

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6380:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '--requirepass redispass'
    networks:
      - nestjs-dashboard-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - nestjs-dashboard-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '18080:80'
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    networks:
      - nestjs-dashboard-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  nestjs-dashboard-network:
    driver: bridge
